@ CRYSTAL_IMPORT_BEGIN: genererad från pokecrystal av tools/crystal_import. Ta bort raden för att handjustera.
CherrygroveMart_MapScripts::
	.byte 0

CherrygroveMart_EventScript_CherrygroveMartClerkScript::
	msgbox CherrygroveMart_Text_CrystalTodo, MSGBOX_NPC
	end

CherrygroveMart_EventScript_CherrygroveMartCooltrainerMScript::
	msgbox CherrygroveMart_Text_CherrygroveMartCooltrainerMText, MSGBOX_NPC
	end

CherrygroveMart_EventScript_CherrygroveMartYoungsterScript::
	msgbox CherrygroveMart_Text_CherrygroveMartYoungsterText, MSGBOX_NPC
	end

CherrygroveMart_Text_CrystalTodo::
	.string "…$"

CherrygroveMart_Text_CherrygroveMartCooltrainerMText::
	.string "They're fresh out\nof POKé BALLS!$"

CherrygroveMart_Text_CherrygroveMartYoungsterText::
	.string "When I was walking\nin the grass, a$"

