@ CRYSTAL_IMPORT_BEGIN: genererad från pokecrystal av tools/crystal_import. Ta bort raden för att handjustera.
PlayersHouse2F_MapScripts::
	.byte 0

PlayersHouse2F_EventScript_PlayersHouseGameConsoleScript::
	msgbox PlayersHouse2F_Text_CrystalTodo, MSGBOX_NPC
	end

PlayersHouse2F_EventScript_PlayersHouseDoll1Script::
	msgbox PlayersHouse2F_Text_CrystalTodo, MSGBOX_NPC
	end

PlayersHouse2F_EventScript_PlayersHouseDoll2Script::
	msgbox PlayersHouse2F_Text_CrystalTodo, MSGBOX_NPC
	end

PlayersHouse2F_EventScript_PlayersHouseBigDollScript::
	msgbox PlayersHouse2F_Text_CrystalTodo, MSGBOX_NPC
	end

PlayersHouse2F_EventScript_PlayersHousePCScript::
	msgbox PlayersHouse2F_Text_CrystalTodo, MSGBOX_SIGN
	end

PlayersHouse2F_EventScript_PlayersHouseRadioScript::
	msgbox PlayersHouse2F_Text_PlayersRadioText1, MSGBOX_SIGN
	end

PlayersHouse2F_EventScript_PlayersHouseBookshelfScript::
	msgbox PlayersHouse2F_Text_CrystalTodo, MSGBOX_SIGN
	end

PlayersHouse2F_EventScript_PlayersHousePosterScript::
	msgbox PlayersHouse2F_Text_CrystalTodo, MSGBOX_SIGN
	end

PlayersHouse2F_Text_CrystalTodo::
	.string "…$"

PlayersHouse2F_Text_PlayersRadioText1::
	.string "PROF.OAK'S POKéMON\nTALK! Please tune\lin next time!$"

