@ CRYSTAL_IMPORT_BEGIN: genererad från pokecrystal av tools/crystal_import. Ta bort raden för att handjustera.
Route29Route46Gate_MapScripts::
	.byte 0

Route29Route46Gate_EventScript_Route29Route46GateOfficerScript::
	msgbox Route29Route46Gate_Text_Route29Route46GateOfficerText, MSGBOX_NPC
	end

Route29Route46Gate_EventScript_Route29Route46GateYoungsterScript::
	msgbox Route29Route46Gate_Text_Route29Route46GateYoungsterText, MSGBOX_NPC
	end

Route29Route46Gate_Text_CrystalTodo::
	.string "…$"

Route29Route46Gate_Text_Route29Route46GateOfficerText::
	.string "You can't climb\nledges.$"

Route29Route46Gate_Text_Route29Route46GateYoungsterText::
	.string "Different kinds of\nPOKéMON appear\lpast here.$"

