@ CRYSTAL_IMPORT_BEGIN: genererad från pokecrystal av tools/crystal_import. Ta bort raden för att handjustera.
CherrygroveGymSpeechHouse_MapScripts::
	.byte 0

CherrygroveGymSpeechHouse_EventScript_CherrygroveGymSpeechHousePokefanMScript::
	msgbox CherrygroveGymSpeechHouse_Text_CherrygroveGymSpeechHousePokefanMText, MSGBOX_NPC
	end

CherrygroveGymSpeechHouse_EventScript_CherrygroveGymSpeechHouseBugCatcherScript::
	msgbox CherrygroveGymSpeechHouse_Text_CherrygroveGymSpeechHouseBugCatcherText, MSGBOX_NPC
	end

CherrygroveGymSpeechHouse_EventScript_CherrygroveGymSpeechHouseBookshelf::
	msgbox CherrygroveGymSpeechHouse_Text_CrystalTodo, MSGBOX_SIGN
	end

CherrygroveGymSpeechHouse_Text_CrystalTodo::
	.string "…$"

CherrygroveGymSpeechHouse_Text_CherrygroveGymSpeechHouseBugCatcherText::
	.string "When I get older,\nI'm going to be a\lGYM LEADER!$"

CherrygroveGymSpeechHouse_Text_CherrygroveGymSpeechHousePokefanMText::
	.string "You're trying to\nsee how good you$"

